<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'Comments\\Actions' => '/controller/Actions.php',
                'Comments\\Comments' => '/model/Comments.php',
                'Comments\\LastView' => '/model/LastView.php',
                'Comments\\Moderation' => '/model/Moderation.php',
                'Comments\\Plugin' => '/model/Plugin.php',
                'Comments\\Stat' => '/model/Stat.php',
                'DLCollection' => '/../DocLister/lib/DLCollection.class.php',
                'DLFixedPrepare' => '/../DocLister/lib/DLFixedPrepare.class.php',
                'DLTemplate' => '/../DocLister/lib/DLTemplate.class.php',
                'DLdebug' => '/../DocLister/lib/DLdebug.class.php',
                'DLpaginate' => '/../DocLister/lib/DLpaginate.class.php',
                'DLpaginateReversed' => '/../DocLister/lib/DLpaginateReversed.class.php',
                'DLphx' => '/../DocLister/lib/DLphx.class.php',
                'DocLister' => '/../DocLister/core/DocLister.abstract.php',
                'DrewM\\MailChimp\\Batch' => '/../FormLister/lib/MailChimp/Batch.php',
                'DrewM\\MailChimp\\MailChimp' => '/../FormLister/lib/MailChimp/MailChimp.php',
                'FormLister\\Activate' => '/../FormLister/core/controller/Activate.php',
                'FormLister\\CaptchaInterface' => '/../FormLister/lib/captcha/Captcha.php',
                'FormLister\\CommentPreview' => '/FormLister/CommentPreview.php',
                'FormLister\\Comments' => '/FormLister/Comments.php',
                'FormLister\\Content' => '/../FormLister/core/controller/Content.php',
                'FormLister\\Core' => '/../FormLister/core/FormLister.abstract.php',
                'FormLister\\DeleteContent' => '/../FormLister/core/controller/DeleteContent.php',
                'FormLister\\DeleteUser' => '/../FormLister/core/controller/DeleteUser.php',
                'FormLister\\FileValidator' => '/../FormLister/lib/FileValidator.php',
                'FormLister\\Filters' => '/../FormLister/lib/Filters.php',
                'FormLister\\Form' => '/../FormLister/core/controller/Form.php',
                'FormLister\\Login' => '/../FormLister/core/controller/Login.php',
                'FormLister\\MailChimp' => '/../FormLister/core/controller/MailChimp.php',
                'FormLister\\Moderation' => '/FormLister/Moderation.php',
                'FormLister\\Profile' => '/../FormLister/core/controller/Profile.php',
                'FormLister\\Register' => '/../FormLister/core/controller/Register.php',
                'FormLister\\Reminder' => '/../FormLister/core/controller/Reminder.php',
                'FormLister\\SubmitProtection' => '/../FormLister/lib/SubmitProtection.php',
                'FormLister\\Validator' => '/../FormLister/lib/Validator.php',
                'Helpers\\Debug' => '/../FormLister/lib/Debug.php',
                'Helpers\\Gpc' => '/../FormLister/lib/Gpc.php',
                'Helpers\\Lexicon' => '/../FormLister/lib/Lexicon.php',
                'Helpers\\Lexicon\\AbstractLexiconHandler' => '/../FormLister/lib/LexiconHandlers/AbstractLexiconHandler.php',
                'Helpers\\Lexicon\\EvoBabelLexiconHandler' => '/../FormLister/lib/LexiconHandlers/EvoBabelLexiconHandler.php',
                'ModxCaptcha' => '/../FormLister/lib/captcha/modxCaptcha/modxCaptcha.php',
                'ModxCaptchaWrapper' => '/../FormLister/lib/captcha/modxCaptcha/wrapper.php',
                'ReCaptchaWrapper' => '/../FormLister/lib/captcha/reCaptcha/wrapper.php',
                'RecentCommentsDocLister' => '/DocLister/RecentComments.php',
                'RuntimeSharedSettings' => '/model/RuntimeSharedSettings.php',
                'SmsCaptchaWrapper' => '/../FormLister/lib/captcha/smsCaptcha/wrapper.php',
                'SmsModel' => '/../FormLister/lib/captcha/smsCaptcha/model.php',
                'TreeViewDocLister' => '/DocLister/TreeView.php',
                'content_DL_filter' => '/../DocLister/core/filter/content.filter.php',
                'extDocLister' => '/../DocLister/core/extDocLister.abstract.php',
                'filterDocLister' => '/../DocLister/core/filterDocLister.abstract.php',
                'jsonHelper' => '/../DocLister/lib/jsonHelper.class.php',
                'onetableDocLister' => '/../DocLister/core/controller/onetable.php',
                'private_DL_filter' => '/../DocLister/core/filter/private.filter.php',
                'sg_DL_filter' => '/../DocLister/core/filter/sg.filter.php',
                'shopkeeperDocLister' => '/../DocLister/core/controller/shopkeeper.php',
                'site_contentDocLister' => '/../DocLister/core/controller/site_content.php',
                'site_content_filtersDocLister' => '/../DocLister/core/controller/site_content_filters.php',
                'site_content_menuDocLister' => '/../DocLister/core/controller/site_content_menu.php',
                'site_content_menu_customDocLister' => '/../DocLister/core/controller/site_content_menu_custom.php',
                'site_content_tagsDocLister' => '/../DocLister/core/controller/site_content_tags.php',
                'sqlHelper' => '/../DocLister/lib/sqlHelper.class.php',
                'tv_DL_filter' => '/../DocLister/core/filter/tv.filter.php',
                'tvd_DL_filter' => '/../DocLister/core/filter/tvd.filter.php',
                'xNop' => '/../DocLister/lib/xnop.class.php'
            );
        }
        if (isset($classes[$class])) {
            require __DIR__ . $classes[$class];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
